services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    depends_on:
      - php
      - db
    networks:
      - app-network

  php:
    build:
      context: ./php
    container_name: php
    volumes:
      - ./php:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:9.0.1
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=bite
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306" # MySQL port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: